Eevee stuff (#1)
* Update gen1.h

HP_ev, attack_ev, defense_ev, speed_ev & special_ev replaced with HP_exp, attack_exp, defense_exp, speed_exp & special_exp

attack_iv, defense_iv, speed_iv & special_iv replaced with attack_dv, defense_dv, speed_dv & special_dv

EVs & IVs are modern terms and work different than Stat Exp and DVs, so I made the changes to reflect terms with accuracy for Gen 1 & 2.

* Update and rename mewdistro.c to eeveedistro.c

Replaced all Mew data for PCNY Growth Eevee with perfect DVs.

Added my name to credits.

Replaced ev for exp and iv for dv, following the same criteria as gen1.h

OT now uses my name.

* Update Makefile

Replaced two instances of Mewdistro for Eeveedistro.

* Update README.md

* Eevee image

* Title and credits messed up

* Update eeveedistro.c

eeveedistro.c:306: error 20: Undefined identifier 'NORMAL_TYPE'
eeveedistro.c:307: error 20: Undefined identifier 'NORMAL_TYPE'
eeveedistro.c:326: error 26: '_special_Dv' not a structure/union member

* Update eeveedistro.c

Trying to make the sprite work, but it need the proper unsigned chat mew_map[] values below

* Update eeveedistro.c

Now the sprite displays properly

* Replacing all Mew terms and constants for Eevee

* Update README.md